language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

osx_image:
  - xcode9.3beta
  - xcode9
  - xcode8
  - xcode6.4

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd test
  - ./testwickedc
